version: "2"
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - C:\Users\sraya\Desktop\minio:/data
      - C:\Users\sraya\Desktop\minio\config:/root/.minio
    environment:
      - "MINIO_ACCESS_KEY=miniominio"
      - "MINIO_SECRET_KEY=miniominio"
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 miniominio miniominio;
      /usr/bin/mc mb myminio/videos;
      /usr/bin/mc mb myminio/thumbnail;
      /usr/bin/mc policy set download myminio/thumbnail;
      /usr/bin/mc policy set download myminio/videos;
      exit 0;
      "